"""jours feries : table de reference

Revision ID: 258f356ab330
Revises: 1f7cf737b496
Create Date: 2026-09-13 16:04:15.553231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '258f356ab330'
down_revision: Union[str, Sequence[str], None] = '1f7cf737b496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicholiday',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicholiday')
    # ### end Alembic commands ###
