"""conges : types, demandes et soldes

Revision ID: 3e1d97ac5e79
Revises: 258f356ab330
Create Date: 2026-09-13 16:06:52.923180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e1d97ac5e79'
down_revision: Union[str, Sequence[str], None] = '258f356ab330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leavetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counts_against_balance', sa.Boolean(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leavetype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leavetype_code'), ['code'], unique=True)

    op.create_table('leavebalance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('acquired', sa.Float(), nullable=False),
    sa.Column('adjustment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leavetype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'year', 'leave_type_id')
    )
    op.create_table('leaverequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_half', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_half', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leavetype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaverequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaverequest_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaverequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaverequest_user_id'))
        batch_op.drop_index(batch_op.f('ix_leaverequest_status'))
        batch_op.drop_index(batch_op.f('ix_leaverequest_start_date'))

    op.drop_table('leaverequest')
    op.drop_table('leavebalance')
    with op.batch_alter_table('leavetype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leavetype_code'))

    op.drop_table('leavetype')
    # ### end Alembic commands ###
