"""utilisateurs : compte actif ou desactive

Revision ID: 75203997c9e2
Revises: d96c528dda1d
Create Date: 2026-09-13 21:50:15.706966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75203997c9e2'
down_revision: Union[str, Sequence[str], None] = 'd96c528dda1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Les comptes existants sont actifs : sans server_default, l'ajout
        # d'une colonne NOT NULL echouerait sur les lignes en place.
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1'))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
