"""tickets : kanban, etiquettes, commentaires, journal

Revision ID: b93483a1ed6a
Revises: 9916a855773c
Create Date: 2026-09-13 16:57:00.472371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b93483a1ed6a'
down_revision: Union[str, Sequence[str], None] = '9916a855773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tk_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tk_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tk_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tk_tickets_status'), ['status'], unique=False)

    op.create_table('tk_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tk_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tk_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tk_comments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('tk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tk_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tk_events_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('tk_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tk_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tk_tags_name'), ['name'], unique=True)

    op.create_table('tk_ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tk_tags.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tk_tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tk_ticket_tags')
    with op.batch_alter_table('tk_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tk_tags_name'))

    op.drop_table('tk_tags')
    with op.batch_alter_table('tk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tk_events_ticket_id'))

    op.drop_table('tk_events')
    with op.batch_alter_table('tk_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tk_comments_ticket_id'))

    op.drop_table('tk_comments')
    with op.batch_alter_table('tk_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tk_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tk_tickets_assignee_id'))

    op.drop_table('tk_tickets')
    # ### end Alembic commands ###
