"""tickets : rattachement a un projet

Revision ID: c82e1589c8cc
Revises: b93483a1ed6a
Create Date: 2026-09-13 17:22:33.987368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c82e1589c8cc'
down_revision: Union[str, Sequence[str], None] = 'b93483a1ed6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tk_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tk_tickets_project_id'), ['project_id'], unique=False)
        # Le mode batch de SQLite reconstruit la table : il lui faut un nom
        # de contrainte explicite pour la retrouver au downgrade.
        batch_op.create_foreign_key(
            'fk_tk_tickets_project', 'project', ['project_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tk_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tk_tickets_project', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tk_tickets_project_id'))
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
